function catMouse(map, moves) {
    if (map.indexOf('m') === -1 || map.indexOf('C') === -1) {
        return 'boring without two animals';
    }

    let indexC, indexM;
    let indexArrC, indexArrM;

    map.split('\n').forEach((el, i) => {
        if (el.indexOf('C') >= 0) {
            indexC = el.indexOf('C');
            indexArrC = i;
        }
        if (el.indexOf('m') >= 0) {
            indexM = el.indexOf('m');
            indexArrM = i;
        }
    });

    let resulLetter = Math.max(indexM, indexC) - Math.min(indexM, indexC);
    let resulArr =
        Math.max(indexArrC, indexArrM) - Math.min(indexArrC, indexArrM);
    return (sum = resulLetter + resulArr) <= moves ? 'Caught!' : 'Escaped!';

    // return sum <= moves ? 'Caught!' : 'Escaped!';
}

// let map =
// `................
// ................
// ............m...
// ..........C.....
// ................
// ................`;
// catMouse(map, 14); // 'Escaped!'); не пойман

// let map =
// `..C......
// .........
// ....m....`;
// catMouse(map, 5); //'Caught!'); поман

let map = `..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
m.....C...
..........
..........
..........
..........
..........`;
catMouse(map, 27); //'Caught!'); поман

// let map = `.C.......
// .........
// ......m..`;
// catMouse(map, 5); // 'Escaped!'); не пойман

// let map =
// `..C......
// .........
// .........`;
// catMouse(map, 5); // 'boring without two animals'); нет мышки
